### ISSUE TITLE
Getting error while installing this package

### ISSUE THREAD

**Issue by ayyappaappana** [weyoss/redis-smq#1]
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "redis-smq" "--save"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ENOSELF

npm ERR! Refusing to install redis-smq as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xxxxxxx\examples\nodejs\redis-smq\npm-debug.log

node -v = 7.0.0

**Comment by weyoss** [comment]
From the log content you posted, it's clear this issue has nothing to do with RedisSMQ itself but with NPM package manager. You should report your issue at  https://github.com/npm/npm/issues .
Furthermore see https://github.com/npm/npm/issues/18018 it should help you.

**Comment by weyoss** [comment]
Closing as not related.
