### ISSUE TITLE
onConsumed throwing error

### ISSUE THREAD

**Issue by apmcodes** [weyoss/redis-smq#10]
https://github.com/weyoss/redis-smq/blob/964f5774bf7ba1d81b029c4f575636bb78756279/src/consumer.js#L301

Should the above line call this[sProcessMessageFailure] instead of throwing error? 

Situation: Our extended consumer class's consume method has a promise, so if any error occurs inside that promise, its being unhandled by the consume method (even though there's a catch) and onConsumed throws that error and halts the process. 

Please guide.

**Comment by weyoss** [comment]
Thank you for point out the error and reporting this issue. 

Actually it's a bug. The fact that the error from promises could not be caught is normal. Promises run asynchronous code and as you know asynchronous errors are uncatchable inside try/catch block (async code run from outside the block) and therefore they are propagated all the way till the consumer is terminated!   

A new release is out which fixes this bug. Please upgrade.

**Comment by weyoss** [comment]
Closing as resolved. Feel free to reopen this issue if it persists.

**Comment by apmcodes** [comment]
Thank you.
