### ISSUE TITLE
Configuration is not present in the redis-smq

### ISSUE THREAD

**Issue by h1t3ndr4** [weyoss/redis-smq#111]
**In the docs it is mentioned that for configuration we will require {Configuration} from the redis-smq but when I did it is coming as undefined. In redis-smq => dist => index do not have Configuration class defined**

To register a configuration object RedisSMQ provides a singleton class that may be used as shown bellow:

'use strict';
const { Configuration, ERedisConfigClient } = require('redis-smq');

const config = {
  redis: {
    client: ERedisConfigClient.IOREDIS,
    options: {
      host: '127.0.0.1',
      port: 6379,
    },
  },
}

Configuration.getSetConfig(config);

but {Configuration} itself it is undefined when I try to require it from redis-smq

**Comment by weyoss** [comment]
It seems that you are using redis-smq@7 and you are referring the documentation for a redis-smq@8 release candidate.

Here is a link for the latest RedisSMQ release [redis-smq@7.2.3](https://github.com/weyoss/redis-smq/tree/v7.2.3)
