### ISSUE TITLE
ReplyError: ERR wrong number of arguments for 'set' command

### ISSUE THREAD

**Issue by anhnam00** [weyoss/redis-smq#13]
Hello everybody,
i had a problem when i run monitor service. 

> PS D:\server\chat-server> node .\monitor-queue.js
Monitor server is running...
D:\server\chat-server\node_modules\redis-smq\src\stats-frontend.js:204
                if (err) throw err;
                         ^
ReplyError: ERR wrong number of arguments for 'set' command
    at parseError (D:\server\chat-server\node_modules\redis-parser\lib\parser.js:193:12)
    at parseType (D:\server\chat-server\node_modules\redis-parser\lib\parser.js:303:14)

I am using node version v7.10.1.
Please help me!
Thank

**Comment by anhnam00** [comment]
i changed from throw to return. It work fine. But i think need fix it.

**Comment by weyoss** [comment]
It seems you have an old Redis version. Please upgrade Redis to the latest version.
Minimal required Redis version is 2.6.12. For more info see https://redis.io/commands/set.
Good luck!

**Comment by weyoss** [comment]
Closing as resolved.

**Comment by anhnam00** [comment]
No. i am using newest redis version: redis_version:2.4.6.
