### ISSUE TITLE
Cron-like scheduling

### ISSUE THREAD

**Issue by haywirez** [weyoss/redis-smq#17]
Is there some support for recurring tasks, similar to Bull? I suspect I could use something like [later](http://bunkat.github.io/later/), but it would be good to know...

**Comment by weyoss** [comment]
Thank you for your interest in this project.

As being a simple message queue and focusing on keeping things simple, this message queue does not support CRON-like scheduling for messages.

I am considering to implement this feature in the next release given that it would not introduce any level of complexity.

This issue will remain open until further updates so keep tuned.

**Comment by weyoss** [comment]
A message scheduler has been implemented. Please upgrade.

**Comment by weyoss** [comment]
Closing as resolved.
