### ISSUE TITLE
Feature Request queue pause/ resume

### ISSUE THREAD

**Issue by apmcodes** [weyoss/redis-smq#18]
Is there any plan to include a pause/ resume queue feature? May be on global level so no worker can consume from the queue until the queue is resumed.

**Comment by weyoss** [comment]
I think pausing/resuming a message queue is a nice option to have.

This feature should be implemented globally and controlled from the RedisSMQ Monitor.

I have plans about refactoring the client side of the monitor and this feature is worth to be included in the planned refactoring.

**Comment by apmcodes** [comment]
Sounds good. Look forward to it. Thanks.
