### ISSUE TITLE
Creating new consumers on the fly

### ISSUE THREAD

**Issue by maheshmahadevan** [weyoss/redis-smq#20]
Hi,

Is it possible to create new consumers on the fly during a running node process rather than have them run separately as a standalone CLI.
Excellent work on creating this SMQ.

Thanks,
Mahesh

**Comment by gemmadlou** [comment]
+1

**Comment by XABRO** [comment]
Hi, any update on this one?

**Comment by weyoss** [comment]
At the MQ level, there are no limitations to do so.  

Even such scenario has not been tested, you can run many consumer from one process. But keep in mind of any of the running consumers throws an error, the rest of consumers will fall down.  

Closing this issue as being open without activity for so long.
