### ISSUE TITLE
Rate limit

### ISSUE THREAD

**Issue by cesarvarela** [weyoss/redis-smq#21]
Is it possible?

thanks

**Comment by weyoss** [comment]
Please provide more details about your suggestion so we can discuss it.

**Comment by cesarvarela** [comment]
I'm building a message queue that uses facebook messenger platform api, and that api is limited to 250 calls/ second, so I need to limit the job precessing of the queue as such.

**Comment by weyoss** [comment]
Sorry for leaving this issue open for so long.

Unfortunately, at this time, this feature is not considered to be implemented. The aim of this project is to provide a simple message queue without a ton of features which could probably make its simplicity disappear. 

Closing this issue for now.
