### ISSUE TITLE
Add delay between retry

### ISSUE THREAD

**Issue by amitava82** [weyoss/redis-smq#24]
I'm trying to figure out how to add delay between retry on error. Neither `setScheduledPeriod` or
`setScheduledDelay` seems to do it. I want to retry a .job `n` number of times only on failure and there must be 10 minutes delay between retry. Is this possible to do?

**Comment by weyoss** [comment]
Both `setScheduledPeriod` and `setScheduledDelay` work for scheduling messages and not for setting up message retry delay upon failure. 

A new parameter `messageRetryDelay`, allowing to wait for an amount of time before retrying a failed message, will be introduced in the next release.

Thank you for reporting this issue.

**Comment by weyoss** [comment]
A new release is out.

**Comment by weyoss** [comment]
Closing as resolved.

**Comment by blurp1478963** [comment]
hello @weyoss 
I have a bug whith the `messageRetryDelay` params:

```js
new Message()
      .setRetryThreshold(3)
      .setRetryDelay(10)
      .setBody(this.message);
```

The first attempt comes à 0,
The second and the third comes 10 sec laters but quite together... there's no more 10 sec delay between attempts...

<img width="592" alt="Capture d’écran 2019-09-06 à 11 28 30" src="https://user-images.githubusercontent.com/16862788/64417621-be223f80-d099-11e9-95fc-52461e8baf74.png">

any idea?

Thanks by advance

**Comment by elribonazo** [comment]
Same issue here, after a task has been failed it does not respect the retryDelay.

**Comment by elribonazo** [comment]
@weyoss Can you please re-open issue.

**Comment by weyoss** [comment]
@elribonazo @elribonazo  @blurp1478963 Reopening the issue for investigation.

**Comment by weyoss** [comment]
The issue has been fixed.

Please upgrade to the latest release!
