### ISSUE TITLE
TypeScript typings

### ISSUE THREAD

**Issue by purplemana** [weyoss/redis-smq#28]
Are they available? I would like to try this package in my TS app.

**Comment by weyoss** [comment]
As for now, RedisSMQ does not provide TypeScript typings. Going to keep this issue open until further updates.

**Comment by sounddroid** [comment]
I second this request!

**Comment by weyoss** [comment]
Happy to let you know that TypeScript is now supported. Please upgrade to v2.x.x.
This is a major upgrade, so make sure to update you code base if you are using deprecated methods.
