### ISSUE TITLE
Support external logger

### ISSUE THREAD

**Issue by purplemana** [weyoss/redis-smq#29]
In a lot of projects there are existing loggers. It'd be great to accept a bunyan compatible logger instance in the options and use that over making one internally. This will allow the host app to use their own levels and transports without duplicating those over to redis-mq.

**Comment by weyoss** [comment]
Starting with redis-smq v6.0.0-rc.9 external loggers are now supported.

**Comment by weyoss** [comment]
Closing as resolved.
