### ISSUE TITLE
How to stop a producer without finish the process?

### ISSUE THREAD

**Issue by dionnyprensa** [weyoss/redis-smq#3]
Need to stop the producer without execute "process.exit(0);"

**Comment by weyoss** [comment]
Version 1.0.7 is out. You can use producer.shutdown() method to gracefully shutdown the producer instance and disconnect from Redis. 
It is worth to note that from that point (after the method has been called) the instance can no longer produce messages. A new instance need to be initialized when needed.
This method has been introduced with the aim of doing some kind of garbage cleaning and system resources releasing when needed, e.g. class destruction.

**Comment by weyoss** [comment]
Closing as resolved.
