### ISSUE TITLE
Receive message on the other queue when restart

### ISSUE THREAD

**Issue by mmsqe** [weyoss/redis-smq#30]
Steps to reproduce:

1. Send message to one Queue1
2. Consumer1 crashes due to error
3. Both Queue1 and Queue2 receive the message from Step1

ps: redis is running with aof

**Comment by weyoss** [comment]
Thank you for reporting this issue!

The cause of this bug has been identified (as being related to GC) and fixed.  

A new release containing this hot-fix will be published today ASAP.

**Comment by weyoss** [comment]
56e3dc00a338a0a418cf9a324e085bedc55ada4f

**Comment by mmsqe** [comment]
Thanks for the quick response, but issue still exists with commit https://github.com/weyoss/redis-smq/commit/64087f154ec40dbdc65e9fa72594970b02351f81

**Comment by weyoss** [comment]
A new release (v1.0.22) is out.

**Comment by mmsqe** [comment]
Sorry that issue has been actually fixed, I didn't delete previous appendonly.aof file mounted from docker container to my host.
