### ISSUE TITLE
Config format not backwards compatible between version 1.0.22 and 1.1.1

### ISSUE THREAD

**Issue by SingHo2016** [weyoss/redis-smq#34]
We recently updated our redis-smq Node package from 1.0.22 to 1.1.1, and our consumers and producers started to fail because it would attempt to connect to 127.0.0.1 instead of the address specified in our config.  Our config file looks like this:

module.exports = {
    namespace: 'dpp-redis-server',
    redis: {
        host: 'our.host.here',
        port: 6379
    },
    log: {
        enabled: 1
    },
    monitor: {
        enabled: true,
        host: '127.0.0.1',
        port: 3000,
    },
};

We noticed that the example config file in the repo has a slightly different configuration than version 1.0.22.  Once we updated the config file, then it works as expected.

However, the biggest issue is that npm updates from 1.0.22 to 1.1.1 without expecting breaking API changes.

Could you look into adding backwards compatibility between configs from version 1.0 into 1.1?

**Comment by weyoss** [comment]
Thank you for reporting the issue.
A new release is out. 
Please upgrade.
