### ISSUE TITLE
what is the cb function?

### ISSUE THREAD

**Issue by dlisage** [weyoss/redis-smq#35]
How do I define the db function? Does this work?
```
const redisSMQ = require('redis-smq');
const ingestion = require('./ingestion');

const { Consumer } = redisSMQ;

class QueueConsumer extends Consumer {
  // eslint-disable-next-line class-methods-use-this
  consume(message, cb) {
    ingestion.myfunction(message);
    cb();
  }
}

module.exports = { QueueConsumer };

And also how do we check if the queue is empty?

**Comment by weyoss** [comment]
I apologize for my late response. 

The callback fn is provided by the message queue to acknowledge/unacknowledge your message. In other words,  it is the way that you can tell the MQ that your message has been either successfully consumed or not. 

Please refer to: 

- https://github.com/weyoss/redis-smq/blob/master/docs/api/consumer.md#consumerprototypeconsume 
- https://github.com/weyoss/redis-smq/blob/master/example/ns1-test-queue-consumer.js 

for more details.

**Comment by weyoss** [comment]
Regarding your second question, at the API level of the MQ there is no method to check if the queue is empty or not. 

Using the RedisSMQ monitor of course you have any information you need (including queues size) about all of your queues, consumers and producers.
