### ISSUE TITLE
Set message Id when producing job

### ISSUE THREAD

**Issue by s888** [weyoss/redis-smq#36]
Hi,
I have recently come across this module.
Does it allow setting message-id to a job like this https://github.com/bee-queue/bee-queue#jobsetidid

I tried bee-queue but it has some bugs which are not acceptable in our case. 

Also, can I provide concurrency to consumers?

**Comment by weyoss** [comment]
Hi,

> Does it allow setting message-id to a job like this https://github.com/bee-queue/bee-queue#jobsetidid

No.

> Also, can I provide concurrency to consumers?

Yes. You can run concurrently as many consumers as you want.
