### ISSUE TITLE
How to set messageRetryThreshold to infinite

### ISSUE THREAD

**Issue by s888** [weyoss/redis-smq#38]
Hi, 

If a consumer throws a message before sending the acknowledgment then it is received after the consumer is restarted. But if the retry attempt is more than 3 then the message is deleted. What should be the value of ```setRetryThreshold```  so that the message is not automatically deleted unless the consumer sends ACK? Have tried setting ```message.setRetryThreshold(-1)``` but it doesn't work. Also, what is the default value of ```messageConsumeTimeout```?

```
//Producer.ts
'use strict';
const { Message, Producer } = require('redis-smq');

const message = new Message();

message
    .setBody({hello: 'worldd!'})
    .setTTL(10800000)

const config = {
    namespace: 'test',
    redis: {
        driver: 'redis',
        options: {
            host: '127.0.0.1',
            port: 6379,
            connect_timeout: 3600000,
        },
    }
}
const producer = new Producer('test_queue',config); //test_queue
producer.produceMessage(message, (err) => {
   if (err) console.log(err);
   else console.log('Successfully produced')
});
```

```
//Consumer.ts
'use strict';

const redisSMQ = require('redis-smq');
const Consumer = redisSMQ.Consumer;

class TestQueueConsumer extends Consumer {
    constructor() {
        super(config)
    }
    consume(message, cb) {
        try{
            console.log('Got a message to consume:', message);
            throw new Error("test")
            //cb();
        } catch(e) {
            console.log("consumer error",e)
        }
        
    }
}

TestQueueConsumer.queueName = 'test_queue';
const consumer = new TestQueueConsumer();
consumer.run();
```

**Comment by weyoss** [comment]
> If a consumer throws a message before sending the acknowledgment then it is received after the consumer is restarted. But if the retry attempt is more than 3 then the message is deleted. 

That's right. By default `messageRetryThreshold` is 3.

> What should be the value of setRetryThreshold so that the message is not automatically deleted unless the consumer sends ACK? Have tried setting message.setRetryThreshold(-1)

You can not do that. Otherwise you get an infinite loop. `messageRetryThreshold` does always have a value. `message.setRetryThreshold(-1)` has the same effect as `message.setRetryThreshold(0)` which means that the message will not be re-queued in case of failure. The maximum `messageRetryThreshold` value is Number.MAX_SAFE_INTEGER (2^53 - 1).
