### ISSUE TITLE
How to jump to the front of the queue?

### ISSUE THREAD

**Issue by bittlingmayer** [weyoss/redis-smq#46]
Let's say we have some items which are higher priority (for example, because they are fast to process).

Is there a recommended way to enqueue them at or near the front of the queue?

**Comment by weyoss** [comment]
All messages are processed in FIFO order. Currently RedisSMQ does not implement a priority queue. Within the next releases, priority queues may be considered to be included as a feature of the MQ. 

Keeping this issue open until further updates.

**Comment by tanguyantoine** [comment]
@weyoss are you looking for help on this one?

**Comment by weyoss** [comment]
Closing this issue as resolved.
