### ISSUE TITLE
Benchmarks promise vs async/await vs bluebird

### ISSUE THREAD

**Issue by intech** [weyoss/redis-smq#48]
> Highly optimized: No promises, no async/await, small memory footprint, no memory leaks. See callbacks vs promises vs async/await benchmarks.

@weyoss i assume this statement is out of date. And the event loop has been optimized to work with async/await.
Please, check this [benchmark](https://gist.github.com/joseluisq/a87adfd46d86d82ba787919a062f6e36)

**Comment by weyoss** [comment]
@intech your assumption is not true.

The point here is about Node.js Callbacks vs Promises.

RedisMQ has been implemented using 100% callbacks. In terms of performance and resource consumption, nothing can beat native Node.js callbacks. 

You are talking about event loop optimizations regarding promises, and showing a benchmark of promises (generators vs async/await vs native promises), which is irrelevant. 

Include callbacks in your list and you will see the difference.

**Comment by intech** [comment]
@weyoss You are right, if you compare with callback, then this is my stupidity.
