### ISSUE TITLE
Duplicate messages in the cron scheduler

### ISSUE THREAD

**Issue by intech** [weyoss/redis-smq#49]
The producer cannot check the existence of the message on restart and duplicates it.
There is no way to set a unique name for a cron task and update it instead of creating duplicates.
There is no way to delete a task that runs regularly.
Thus, the use of cron tasks loses all meaning, without being able to manage them and control their work.

**Comment by weyoss** [comment]
@intech 

> The producer cannot check the existence of the message on restart and duplicates it.

Well, the producer is stateless and upon restart when asked to publish a message, it just publishes it. I believe that it is not its responsibility to check if such message has been published before. You should implement such logic in your application.

> There is no way to set a unique name for a cron task and update it instead of creating duplicates.
> There is no way to delete a task that runs regularly.
> Thus, the use of cron tasks loses all meaning, without being able to manage them and control their work.

Now there I agree with you. I think it's a good point. Considering to add this feature.

I will keep you updated.

**Comment by weyoss** [comment]
@intech 

New methods (scheduler.getScheduledMessages(), scheduler.deleteScheduledMessage()) has been added allowing to fetch and deleted scheduled messages.

Please upgrade your RedisSMQ installation.

**Comment by weyoss** [comment]
Closing this issue as resolved.
