### ISSUE TITLE
Typescript error

### ISSUE THREAD

**Issue by AlexRypun** [weyoss/redis-smq#52]
Typescript can't compile because of an error.
In `types/config.ts` interface `ConfigInterface` extends `Monitor.ConfigInterface`

```
export interface ConfigInterface extends Monitor.ConfigInterface {
    namespace?: string,
    redis: {
        driver: ConfigRedisDriver,
        options: {
            [key:string]: any
        }
    },
    log?: {
        enabled: boolean,
        options: {
            [key:string]: any
        }
    },
}
```
but `redis` is not suitable for `Monitor.ConfigInterface` interface, because of different types of `driver`. They look equal, but that's different enums.
```
export enum ConfigRedisDriver {
    REDIS = "redis",
    IOREDIS = "ioredis"
}
```
and 
```
export enum RedisDriver {
    REDIS = 'redis',
    IOREDIS = 'ioredis'
}
```
In version 2.0.0 there wasn't inheritance and there wasn't a typescript error. In 2.0.1 it was added.

**Comment by nmokkenstorm** [comment]
Running into the same issue, would love this to be merged

**Comment by weyoss** [comment]
This issue has been fixed. Please upgrade RedisSMQ to v3. If you encounter any new issue please let me know.

**Comment by weyoss** [comment]
Closing as resolved
