### ISSUE TITLE
Crash on redis master failover

### ISSUE THREAD

**Issue by smdesmet** [weyoss/redis-smq#57]
Hi,

We are running in a redundant redis setup with sentinels. When I kill the master redis(kill the VM), it takes a while for a redundant master to take over. During that time, I guess an error is sent by ioredis and, since that error is thrown by the redis-client, it never gets caught.
Is there a reason why there is no recovery after a transient redis error
 this.client.once('error', (err: Error) => {
    throw err;
 });
    
Thanks

**Comment by weyoss** [comment]
@smdesmet 

The MQ can not recover on its own from an unexpected error,  for example a Redis error. To avoid any unpredicted behaviour, the error is thrown and the consumer process is crashed. 

This is a good practice. 

It’s up to your application/environment to decide what to do in such case. 

You have many options. For example you can monitor your running consumer process using a process manager tool, pm2 for example, so in case of a consumer crash, the process is restarted. 

Another option for example is to configure Redis client to not return an error immediately upon server shutdown and to try to reconnect. RedisSMQ supports all Redis configuration parameters for both ioredis and node_redis clients.

I recommend to consider the first option.

**Comment by weyoss** [comment]
It seems that ioredis always emit an error even when configured to retry to reconnect. 

Going to investigate the issue.

**Comment by weyoss** [comment]
For the second option, a fix has been made allowing Redis client to recover when configured to do so.

Please upgrade your RedisSMQ installation.

Thank you for reporting this issue.

**Comment by weyoss** [comment]
Closing as resolved.
