### ISSUE TITLE
"Can not switch state while another state transition is in progress." - when consumer.shutdown() is called twice

### ISSUE THREAD

**Issue by PhantomRay** [weyoss/redis-smq#59]
Hi there.

While consumer is running, when I call `consumer.shutdown()` twice, the second call throws `Can not switch state while another state transition is in progress.` error. 

Actual: 
```js
     consumer.shutdown();
     try {
        consumer.shutdown();
      } catch (err) {
       // error caught as "Can not switch state while another state transition is in progress."
        console.error(err.message);
      }
```

Actual:
```js
    consumer.shutdown();
    consumer.shutdown((err)=>{
        // unable to catch "Can not switch state while another state transition is in progress." error
    });
```

IMO, any error should be thrown to the callback in `shutdown(cb)`.

Expect:
```js
    consumer.shutdown();
    consumer.shutdown((err)=>{
        // catch error here
    });
```

**Comment by weyoss** [comment]
@PhantomRay 

Fatal errors are always explicitly thrown to crash the process. 

I don't know why you need to call the `shutdown` method twice, neither the MQ does. So it yells at you ) to figure out what is going wrong.

Normally If you need to wait until the consumer/producer is completely shutdown you should provide a callback function.

**Comment by weyoss** [comment]
To check if an instance is running the Consumer class provides `isRunning()` method.

**Comment by PhantomRay** [comment]
hi @weyoss thanks for your reply. Yes, meanwhile I use isRunning to address that. 

But ideally, would be good to throw error in that callback if possible. Just my opinion. 

Otherwise you can close this issue.

**Comment by weyoss** [comment]
I think it is a good practice to shutdown the consumer only from one place. So if you accidentally called `shutdown` from other place, the error is thrown without the possibility to recover from it. That's the point. 

When designing the MQ I was very strict about this behaviour.

Thanks for your feedback!

**Comment by weyoss** [comment]
Closing as resolved.

**Comment by weyoss** [comment]
From redis-smq@6.0.0-rc8 errors are no more thrown when calling run() and shutdown() methods multiple times. 

A status has been introduced to indicate whether the operation completed successfully.

```javascript
consumer.shutdown((err, status)=>{
    // status is true
});
consumer.shutdown((err, status)=>{
    // status is false
});
consumer.shutdown((err, status)=>{
    // status is false
});
```

**Comment by weyoss** [comment]
@PhantomRay FYI
