### ISSUE TITLE
MultiQueueProducer doesn't seem to work [6.0.0-rc.4]

### ISSUE THREAD

**Issue by PhantomRay** [weyoss/redis-smq#60]
Hi there, with `Producer`, I'm able to produce/consume the message, but with `MultiQueueProducer`, it seems it doesn't work.

## This works

```
const { Consumer, Producer, Message } = require('redis-smq');
const queue = 'S-12345'

const message = new Message();
message
    .setBody({ hello: 'world', ts: new Date() })
    .setTTL(3600000);

const producer = new Producer(queue);

setInterval(() => {
    producer.produce(message, (err) => {
        if (err) console.log(err);
        else console.log('Successfully produced')
    });
}, 1000);

class TestQueueConsumer extends Consumer {
    consume(message, cb) {
        console.log('Got a message to consume:', message.body);
        cb();
    }
}

const consumer = new TestQueueConsumer(queue);
consumer.run();
console.log('consumer running')
```

## This doesn't work

```
const { Consumer, MultiQueueProducer, Message } = require('redis-smq');

const queue = 'S-12345'

const message = new Message();
message
    .setBody({ hello: 'world', ts: new Date() })
    .setTTL(3600000);

const producer = new MultiQueueProducer();

setInterval(() => {
    producer.produce(queue, message, (err) => {
        if (err) console.log(err);
        else console.log('Successfully produced')
    });
}, 1000);

class TestQueueConsumer extends Consumer {
    consume(message, cb) {
        console.log('Got a message to consume:', message.body);
        cb();
    }
}

const consumer = new TestQueueConsumer(queue);
consumer.run();
console.log('consumer running')
```

Anything wrong? Thanks in advance.

**Comment by weyoss** [comment]
Hey @PhantomRay 

The code coverage of redis-smq is actually 87%, MultiQueueProducers are fully  covered with test. The tests are passing.

Probably you have something wrong with your setup and environment.

I am going to try to run your example just to make sure that everything is OK.

**Comment by weyoss** [comment]
Thank you for opening this issue. 

I will keep you updated.

**Comment by weyoss** [comment]
@PhantomRay 

I can definitely confirm that there is a minor bug, but critical, in MultiQueueProducer which was introduced in 6.0.0-rc.4 pre-release. The bug was not covered by tests.

I am going ASAP to fix the issue and cover it with a new test.

You help is valuable.  Thank you )

**Comment by PhantomRay** [comment]
As always, thank you very much for looking into it.

**Comment by weyoss** [comment]
This issue has been fixed. 

Please Update redis-smq to the latest release.

Feel free to open a issue if you need any help.

**Comment by weyoss** [comment]
Closing as resolved.
