### ISSUE TITLE
[Priority Queues] Message delivery order for messages with same priority

### ISSUE THREAD

**Issue by PhantomRay** [weyoss/redis-smq#61]
Hi @weyoss , just a simple question.
For messages with same priority, are they delivered in LIFO manner?

**Comment by weyoss** [comment]
@PhantomRay Questions are always welcome.

When you set a priority for a message, it is always enqueued in the priority queue.

If two messages or more have the same priority, then are delivered according to their lexicographical order (alphabetical).

Message objects are stored in a text format using JSON.stringify, so the  alphabetical ordering will be based on the whole serialized string (not on the message payload).

**Comment by PhantomRay** [comment]
Thank you for your explanation.
