### ISSUE TITLE
configurable namespace

### ISSUE THREAD

**Issue by apmcodes** [weyoss/redis-smq#7]
It would be helpful to have a configurable namespace instead of the default hard coded ns _redis-smq_, via the config file. Helpful in cases where redis-smq is a module of a larger redis based projects.

**Comment by weyoss** [comment]
First of all, thank you for your suggestion. I believe we need to configure the RedisSMQ namespace for each project, let it be a big project or a small one. Using one global namespace `redis-smq` can lead sometimes to collisions between queue names from different projects. 
The next release will include this improvement. Have a nice day!

**Comment by apmcodes** [comment]
Thanks!
