### ISSUE TITLE
Question: how do consumers make use of redis connection?

### ISSUE THREAD

**Issue by PhantomRay** [weyoss/redis-smq#70]
My web service creates a new consumer every time when a client makes a websocket connection. So if there were 10k websocket 
connections, there will be 10k consumers.

How does consumer make use of redis connections? Will it be 10k redis connection or share just a connection pool.

**Comment by weyoss** [comment]
> My web service creates a new consumer every time when a client makes a websocket connection. So if there were 10k websocket

You should not do such a thing. Creating a new consumer for each connection is a bad pattern. Even, if considering that you have tiny consumers without Redis connections. You are going to to exhaust your system resources. 

> How does consumer make use of redis connections? Will it be 10k redis connection or share just a connection pool.

No. You can not make use of internal Redis connections of a consumer.

**Comment by PhantomRay** [comment]
My use case is each user has a message queue. So when they connect to the backend with a persistent connection (e.g. ws), they will receive messages retrieved by consumers. While they are connected, the consumers are always running.

`A consumer may consume messages from many queues.` - I think this is what I'm after. I will do some test on my side.

Thank you again!
