### ISSUE TITLE
Request to change the redis key format

### ISSUE THREAD

**Issue by PhilHannent** [weyoss/redis-smq#73]
This project is going to become the backbone of a lot of my projects, thank you.

I have a request to make regarding the key format you are using with redis:

<img width="363" alt="image" src="https://user-images.githubusercontent.com/813874/154840319-9c503bf3-3136-4790-8843-531ab4b4dc8e.png">

Most Redis GUI clients will split on a colon `:` allowing you to have folders in effect:

<img width="219" alt="image" src="https://user-images.githubusercontent.com/813874/154840362-053f8e53-acca-47f4-86c3-d1322ba1c68f.png">

Can I request that you change from using hyphens to using colons?

**Comment by weyoss** [comment]
Thank you for opening this issue.

> This project is going to become the backbone of a lot of my projects, thank you.

It's my pleasure.

Please pay attention that Redis key segments are joined by dots `.` and not by hyphens `-`. So I suggest you mean replacing dots by colons.

I think It would be a nice improvement towards better experience with many Redis GUI clients. 

I will keep updated.

**Comment by weyoss** [comment]
Closing as resolved.
