### ISSUE TITLE
Invalid rateLimit.interval. Expected a positive integer >= 1000

### ISSUE THREAD

**Issue by PhilHannent** [weyoss/redis-smq#76]
Hi,

We are implementing the rate limit and have found an unexpected error:
`Invalid rateLimit.interval. Expected a positive integer >= 1000`

We are talking to a legacy API and its performance means we want to limit the number of requests to it so we have chosen a safe value of 1 request every half a second:

`queueManager.setQueueRateLimit(queueName, { limit: 1, interval: 500 }, (errInner) => {`

We were hoping to lower this once we are sure the production system can handle the request load. Can the check for the interval be lower?

**Comment by weyoss** [comment]
The minimum value of 1 sec for rate limiting interval is required for various reasons:

- JavaScript timers (setTimeout() and setInterval()) are not accurate enough and are allowed to drift (in my experience from 500 ms to 1-2 seconds) and using a value of less than 1 sec for rate limiting is useless.
- When a rate limit is set, messages are dequeued from a queue using pooling with a wait time (timeout) of 1sec. Using a value less than 1 second would create a significant load on Redis server with a huge number of requests. 

> We were hoping to lower this once we are sure the production system can handle the request load. Can the check for the interval be lower?

No. You should consider adjusting your rate limit interval with a value no less than 1 sec.

**Comment by weyoss** [comment]
Closing as resolved.
