### ISSUE TITLE
tiny bug

### ISSUE THREAD

**Issue by apmcodes** [weyoss/redis-smq#8]
consumer.js
In line 220, its should be message.uuid instead of message.id
this[sLogger].error(`Consumer failed to consume message [${message.id}]...`);

so minor :)

**Comment by weyoss** [comment]
I am happy that you are enjoying and playing my code. Good catch! :)

**Comment by apmcodes** [comment]
Yes. Redis-smq is really simple and awesome message queue. Have become my goto mesaage queue for node projects. 

Thank you very much.
