### ISSUE TITLE
Feature request: Topic based routing 

### ISSUE THREAD

**Issue by affohsalif93** [weyoss/redis-smq#80]
Do you plan on implementing any kind of topic based routing? much like a message broker?  Awesome library BTW.

**Comment by weyoss** [comment]
Thank you for opening this issue.

I am not sure if we can implement topic based routing without sacrificing performance.

Keeping this issue open until further updates.

**Comment by weyoss** [comment]
**UPD**: This feature is currently under active development and will be introduced in v7.1.0 release which will bring 3 new exchanges (transports) for publishing messages:

- Direct Exchange: a message is published based on an exact match with the specified queue.
- Topic Exchange: a message is published based on a pattern match.
- Fanout Exchange: a message is published to all queues that are bound to a given binding key.

**Comment by weyoss** [comment]
Closing as resolved.
