### ISSUE TITLE
Cannot serialize `bigint`

### ISSUE THREAD

**Issue by neelkamath** [weyoss/redis-smq#81]
Trying to pass a value as a `bigint` fails with an error message stating that `bigint`s can't be serialized. I'm currently converting the `bigint` to a `string` before passing it to `redis-smq`'s producer, and then converting the `string` back to a `bigint` in the consumer. If this could be done under the hood, that'd be great.

Or are `bigint`s unsupported because JSON is being used as a transport? Even though JSON doesn't have a limitation on integer size, I know JavaScript does, and since the JSON is being handled via JS, this problem would bubble up to users of `redis-smq`.

**Comment by weyoss** [comment]
RedisSMQ uses JSON as a data format for storing messages in Redis. 

JSON does not support BigInt.

If you try to serialize an object with a BigInt property you will get an exception:

```javascript
const r = {bigint: 15n};
JSON.stringify(r);
// TypeError: Do not know how to serialize a BigInt
```

If your application does rely on BigInts, as a workaround, you can convert BigInt fields to strings before publishing a message.
