### ISSUE TITLE
Redis smq randomly throws an error that make app crashes 

### ISSUE THREAD

**Issue by longtt2705** [weyoss/redis-smq#83]
I'm using RedisSMQ to communicate between services in my project. When the app has RedisSMQ running for a while, it randomly throw an error like below. 
<img width="713" alt="image" src="https://user-images.githubusercontent.com/47821138/163846996-795db415-d0d3-4a1f-bdbb-e67ed69eb9fa.png">
All I have to do is restart the app and it works normally, but it will crash again and this issue happens from time to time. 
I know that we can deal with it by using `forever` package. But I want to know what causes this problem and how to fix it exactly.

**Comment by weyoss** [comment]
@longtt2705 Thank you for opening this issue.

It seems that the acquired lock expires before being extended. The default lock expiration is 10s. 

If a given process takes more time than 10s to perform a task then this error may be thrown. 

A fix will be published later. 

I will keep you updated.

**Comment by weyoss** [comment]
This issue has been resolved in release v6.4.2.
