### ISSUE TITLE
Producer & Consumer seem to be ignoring config

### ISSUE THREAD

**Issue by franzwarning** [weyoss/redis-smq#88]
Hi,

I'm setting my producer up using `new Producer(config)` where the config looks like this:

```
export const redisConfiguration: IConfig = {
    namespace: 'latitude-worker',
    redis: {
        client: RedisClientName.IOREDIS,
        options: {
            connectTimeout: 3600000,
            host: 'redis',
            password: '',
            port: 6379,
            family: process.env.NODE_ENV === 'production' ? 6 : 4,
            db: 0,
        },
    },
    logger: {
        enabled: true,
        options: {
            level: 'info',
        },
    },
    messages: {
        store: false,
    },
}
```

but for some reason I'm gettin this message:
```
worker_1  | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
```

seems like ioredis is ignoring the custom host I set `'redis'`?

It's clearly working for `QueueManager.createInstance(redisConfiguration`, because it creates the queues... but not for the producer and consumer.

Would love some help here

**Comment by weyoss** [comment]
@franzwarning Thank you for opening this issue.

Are you using the latest release candidate (7.0.0-rc.6)?

**Comment by franzwarning** [comment]
> @franzwarning Thank you for opening this issue.
> 
> Are you using the latest release candidate (7.0.0-rc.6)?

Yes

**Comment by weyoss** [comment]
Also the config is not ignored when using `RedisClientName.IOREDIS` client.

```shell
$ node dist/index.js
[consumer:95c36796-f86c-437b-bae5-3f689e1652a7] Going up...
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.199:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.199:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
...
```

**Comment by weyoss** [comment]
Closing as irrelevant.
