### ISSUE TITLE
Need to support redis AUTH

### ISSUE THREAD

**Issue by apmcodes** [weyoss/redis-smq#9]
Currently, redis password is not used while creating redis connection. Need to support redis password and  db.

Please suggest, should the getNewInstance (redis-client.js) be modified to include password and db or is there a better way to do it without touching this library files.

Thank you.

**Comment by weyoss** [comment]
Starting from release 1.0.10 all Redis parameters are supported including authentication. See https://github.com/weyoss/redis-smq#configuration for more details. If something went wrong or your are having issues with authentication please let me know.

**Comment by apmcodes** [comment]
Updated redis-smq to the latest version (1.0.12), and authentication works fine. Thank you.

**Comment by apmcodes** [comment]
config update needs to be applied for Monitor as well.

const client = redis.createClient(config.redis.port, config.redis.host);

**Comment by weyoss** [comment]
Cleaned up the code. Please upgrade.

**Comment by weyoss** [comment]
Closing as resolved.
