### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by hiendaovinh** [weyoss/redis-smq#91]
Hi,
I was trying to produce multiple messages and encountered this warning
```
(node:1055180) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 up listeners added to [Producer]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:601:17)
    at Producer.addListener (node:events:619:10)
    at Producer.once (node:events:663:8)
    at Producer.produce (node_modules/redis-smq/dist/src/lib/producer/producer.js:94:26)
```

It's from the `once(events.UP, proceed)`.

**Comment by weyoss** [comment]
Hey @hiendaovinh! Thank you for reporting this issue.

I'm going to see what went wrong ASAP.

**Comment by weyoss** [comment]
My first though is, this error may occur only in one case:  When you create a producer instance, it will try to connect to Redis immediately. At time when your producer instance is not yet fully UP, you tried to publish too much messages. So in this case I expect an exception to be thrown (MaxListenersExceededWarning).

**Comment by weyoss** [comment]
After a quick analysis, it seems like you tried **concurrently** from many places, using a single producer instance which has not yet connected to Redis, to publish many messages. 
 
Just to keep things simple and to avoid this kind of errors, maybe producer instances should be manually started using the `run()` method, the same way as for consumers.

**Comment by hiendaovinh** [comment]
Yes @weyoss,
I was using a single producer to produce multiple messages concurrently. Do you have any recommendation for this kind of pattern? Should I create multiple producers? I got like a thousand of messages to process.

**Comment by hiendaovinh** [comment]
You were mentioning `run()` but afaik it's [automatically called at constructor](https://github.com/weyoss/redis-smq/blob/master/src/lib/producer/producer.ts#L16-L19).
Should I listen for up events before start producing?

**Comment by hiendaovinh** [comment]
Yeah, I can confirm this will work. I think you should update your documentation.
```
const producer = new Producer(config)
producer.once(events.UP, () => {
  producer.produce(message, err => {})
  ...
})
```

Although producer automatically run, it doesn't guarantee that it's ready. We need to wait for the signal before pushing to avoid this kind of warning.

**Comment by weyoss** [comment]
> Do you have any recommendation for this kind of pattern? Should I create multiple producers? I got like a thousand of messages to process.

Producing concurrently many messages, a thousand or a million messages, is totally fine as well as your system can handle it. So the recommended way is to use a single producer instance.

**Comment by weyoss** [comment]
> You were mentioning run() but afaik it's [automatically called at constructor](https://github.com/weyoss/redis-smq/blob/master/src/lib/producer/producer.ts#L16-L19).

At this time the `run()` method is automatically called upon initialization. But I mean as an improvement it shouldn't be that way and this should be changed to manually calling the `run()` method, like you do for consumers. The point is that the `run()` method accepts a callback and once the producer is ready and running the callback get called. After that you can do whatever you want with your producer.

**Comment by weyoss** [comment]
```
const producer = new Producer(config)
producer.once(events.UP, () => {
  producer.produce(message, err => {})
  ...
})
```

This is a workaround, it should be fine for now.

**Comment by hiendaovinh** [comment]
Agree. Thank you for your time!

**Comment by weyoss** [comment]
It was my pleasure. 

Reopening this issue as an improvement is required to be made to avoid this kind of issues.

**Comment by hiendaovinh** [comment]
I think we should just put a notice to the documentation for awareness and let people decide how to use it properly.

**Comment by weyoss** [comment]
> I think we should just put a notice to the documentation for awareness and let people decide how to use it properly.

Starting with v7.0.6, the proper way is to run your producer instance using the `run()` method.

**Comment by weyoss** [comment]
See https://github.com/weyoss/redis-smq/blob/master/docs/api/producer.md#producerprototyperun

**Comment by weyoss** [comment]
Closing as resolved.
