### ISSUE TITLE
LockManagerExtendError: Acquired lock could not be extended

### ISSUE THREAD

**Issue by hiendaovinh** [weyoss/redis-smq#93]
Hi, I was experiencing this fatal error randomly and hope could you shed some light on this please.
Observing the interval of `PEXPIRE` sometimes I saw a hang when you couldn't renew the expiration (TTL eventually results in -2).

The queue is setup without multiplexing and `message.setConsumeTimeout` at a much higher interval

**Comment by weyoss** [comment]
@hiendaovinh Thank you for reporting this issue.

I am going to investigate the issue ASAP.

I Will keep you updated. Please stay tuned.

**Comment by weyoss** [comment]
This issue has been resolved in redis-smq@v7.0.7

**Comment by weyoss** [comment]
Closing as resolved.
