### ISSUE TITLE
How to delete message in consumer

### ISSUE THREAD

**Issue by meawadhesh** [weyoss/redis-smq#96]
Hi, thanks for the amazing library.
I scheduled message at particular time and i would like to delete after 1 execution of scheduled time in consumer `consumer.consume` here i have message with dynamic data. how to delete a particular message?

**Comment by weyoss** [comment]
@meawadhesh Hey! Thank you for opening this issue.

> Hi, thanks for the amazing library.

I am glad that you are using it.

> I scheduled message at particular time and i would like to delete after 1 execution of scheduled time in consumer consumer.consume here i have message with dynamic data. how to delete a particular message?

There are 2 types of scheduled messages: 

- **Periodic Scheduled Messages**: Messages that are scheduled to be delivered periodically using a [setScheduledRepeat()](https://github.com/weyoss/redis-smq/blob/master/docs/api/message.md#messageprototypesetscheduledrepeat) or [setScheduledCRON()](https://github.com/weyoss/redis-smq/blob/master/docs/api/message.md#messageprototypesetscheduledcron)

- **One time scheduled messages**: Any other scheduled messages.

A one time scheduled message is deleted from the `scheduled messages queue` once its scheduled timestamp expires. So there is no need to manually delete it.

A periodic scheduled message can be deleted from `scheduled messages queue` by its ID using [MessageManager.prototype.scheduledMessages.delete()](https://github.com/weyoss/redis-smq/blob/master/docs/api/message-manager.md#messagemanagerprototypescheduledmessagesdelete).

**Comment by weyoss** [comment]
> A one time scheduled message is deleted from the scheduled messages queue once its scheduled timestamp expires. So there is no need to manually delete it.

it is worth to mention that a one time scheduled message can also be manually deleted, given that at the deletion time the message is still in the `scheduled messages queue`.

**Comment by weyoss** [comment]
Closing as resolved.

**Comment by meawadhesh** [comment]
Hi, 
Thanks for the reply. I'll implement this asap.
