### ISSUE TITLE
Error: ENOENT: no such file or directory, open '../lua/zpophgetrpush.lua

### ISSUE THREAD

**Issue by namnguyen279** [weyoss/redis-smq#99]
Current version 7.2.0 throw error when create QueueManager under Mono Repo setup, it resolved to incorrect folder to resolve internal file ..

**Comment by weyoss** [comment]
@namnguyen279 Thank you for opening this issue. 

A new release has been published.

Please update both redis-smq and redis-smq-common. You should be using at least redis-smq@7.2.1 and redis-smq-common@1.0.6 or newer releases.

Let me know if your issue is still present.

**Comment by weyoss** [comment]
Closing as resolved.
